name: OPTYVA
favicon: null
layout_spectrum: 0.9670818564482033
typography_spectrum: 0.45891264686360955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99aa33'
    - '#4c554c'
    - '#332d33'
    - '#7f727f'
  brandStrength: 0.897009662585333
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
